AWSTemplateFormatVersion: 2010-09-09
Resources:
  lambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  dictionariesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'dw-bootstrap-artifactstorebucket-15ca1vm75gune'
        S3Key: 'deutsch-wiederholen/lambda/lambdas-1.0-SNAPSHOT-all.jar'
      Description: 'Lambda handling dictionaries queries'
      Handler: 'dw.Hello'
      MemorySize: 128
      Role: !GetAtt lambdaExecutionRole.Arn
      Runtime: 'java8'
      Timeout: 10
      Tags:
        - Key: project
          Value: DeutschWiederholen

  restApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'Dictionaries'
      Description: 'Returns dictionaries'
      EndpointConfiguration:
        Types: ['EDGE']

  restApiNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApi.RootResourceId
      PathPart: '{name+}'
      RestApiId: !Ref restApi

  restApiGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/${dictionariesLambda.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
      RequestParameters:
        method.request.path.name: true
      CacheKeyParameters:
        - 'method.request.path.name'
      ResourceId: !Ref restApiNameResource
      RestApiId: !Ref restApi
