AWSTemplateFormatVersion: 2010-09-09
Resources:
  lambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  dictionariesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'dw-bootstrap-artifactstorebucket-15ca1vm75gune'
        S3Key: 'deutsch-wiederholen/lambda/lambdas-1.0-SNAPSHOT-all.jar'
      Description: 'Lambda handling dictionaries queries'
      Handler: 'dw.Hello'
      MemorySize: 128
      Role: !GetAtt lambdaExecutionRole.Arn
      Runtime: 'java8'
      Timeout: 10
      Tags:
        - Key: project
          Value: DeutschWiederholen

  restApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'Dictionaries'
      Description: 'Returns dictionaries'
      EndpointConfiguration:
        Types: ['EDGE']

  restApiRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApi.RootResourceId
      PathPart: '{name+}'
      RestApiId: !Ref restApi
