AWSTemplateFormatVersion: 2010-09-09
Description: DeutschÜben project infrastructure description
Resources:
  vpcDeutschUeben:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.30.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      Tags:
        - Key: Name
          Value: deutschÜben
        - Key: project
          Value: deutschÜben
  subnetDeutschUebenBackendC:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 172.30.100.0/24
      AvailabilityZone: eu-central-1c
      VpcId: !Ref vpcDeutschUeben
      Tags:
        - Key: Name
          Value: deutschÜben-backend-c
        - Key: project
          Value: deutschÜben
  subnetDeutschUebenFrontendC:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 172.30.1.0/24
      AvailabilityZone: eu-central-1c
      VpcId: !Ref vpcDeutschUeben
      Tags:
        - Key: Name
          Value: deutschÜben-frontend-c
        - Key: project
          Value: deutschÜben
  igwDeutschUeben:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: deutschÜben
        - Key: project
          Value: deutschÜben
  aclDeutschUeben:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref vpcDeutschUeben
      Tags:
        - Key: Name
          Value: deutschÜben
        - Key: project
          Value: deutschÜben
  rtDeutschUeben:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref vpcDeutschUeben
      Tags:
        - Key: Name
          Value: deutschÜben
        - Key: project
          Value: deutschÜben
  sgDeutschUebenWeb:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Default DeutschUeben security group'
      VpcId: !Ref vpcDeutschUeben
      Tags:
        - Key: Name
          Value: deutschÜben
        - Key: project
          Value: deutschÜben
  acl1:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref aclDeutschUeben
  acl2:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref aclDeutschUeben
  subnetacl1:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref aclDeutschUeben
      SubnetId: !Ref subnetDeutschUebenFrontendC
  subnetacl2:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref aclDeutschUeben
      SubnetId: !Ref subnetDeutschUebenBackendC
  gw1:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref vpcDeutschUeben
      InternetGatewayId: !Ref igwDeutschUeben
  route1:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref rtDeutschUeben
      GatewayId: !Ref igwDeutschUeben
    DependsOn: gw1
  dchpassoc1:
    Type: 'AWS::EC2::VPCDHCPOptionsAssociation'
    Properties:
      VpcId: !Ref vpcDeutschUeben
      DhcpOptionsId: dopt-cfeb07a4
  ingress1:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgDeutschUebenWeb
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
  ingress2:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgDeutschUebenWeb
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  ingress3:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgDeutschUebenWeb
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 0.0.0.0/0
  ingress4:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgDeutschUebenWeb
      IpProtocol: icmp
      FromPort: '-1'
      ToPort: '-1'
      CidrIp: 0.0.0.0/0
