AWSTemplateFormatVersion: 2010-09-09
Resources:
  lambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  restApi:
    Type: AWS::ApiGateway::RestApi
    Name: 'Dictionaries'
    Properties:
      Description: 'Returns dictionaries'
      EndpointConfiguration:
        Types: ['EDGE']

  restApiRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApi.RootResourceId
      PathPart: '{name+}'
      RestApiId: !Ref restApi
